name: Build Theme
on:
  push:
    branches:
    - master
jobs:
  theme:
    name: Push (merge) to master
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install and build
      run: |
        composer install --no-dev
        npm install
        npm run build
    - name: Push to Theme
      env:
        GITHUB_REPOSITORY: ${{ github.event.repository.name }}
        GITHUB_SHA: ${{ github.event.commits[0].sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "dinhtungdu@gmail.com"
        git config --global user.name "Tung Du"
        git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        rm -rf node_modules
        rm -rf .editorconfig
        rm -rf .gitignore
        rm -rf .caches
        rm -rf *.config.js
        rm -rf composer.json
        rm -rf composer.lock
        rm -rf package.json
        rm -rf package-lock.json
        rm -rf .github
        mkdir /tmp/release
        cp -a ./ /tmp/release
        git worktree prune
        git fetch
        git worktree add -B theme release origin/theme
        cd release
        cp -rf /tmp/release/* .
        git add .
        git commit -m "Committing built version of $GITHUB_SHA"
        git push origin theme
